
import { AIPendingAction, Language } from "./portulToolchainService";
import { getKnowledgeAxiom, NAMING_STYLE_MASK } from './aiLearningService';
import { translations } from "../utils/translations";

// --- Axiom-Aware Naming Conventions ---
const toClassName = (base: string, axiom: number): string => {
    const useCamelCase = (axiom & NAMING_STYLE_MASK) !== 0;
    if (useCamelCase) {
        return base.split(/[\s_]+/).map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('');
    }
    return base.replace(/\s+/g, '_').toLowerCase();
};

const toFileName = (base: string): string => base.replace(/\s+/g, '_').toLowerCase();


// --- Axiom-Aware Code Generation Templates ---
const createLoggerCode = (axiom: number): { content: string, className: string } => {
    const className = toClassName('Logger', axiom);
    const fileName = toFileName(className);
    const content = `
# ${fileName}.portulpp (Auto-generated by Aether Core)
# A simple utility for logging messages.

class ${className} {
    private txt prefix;

    new ${className} txt prefix {
        mov this.prefix prefix;
    }

    public log txt message {
        put this.prefix;
        put ": ";
        put message;
    }
}
`;
    return { content, className };
};

const createAdvancedLoggerCode = (axiom: number): { content: string, className: string } => {
    const className = toClassName('Logger', axiom);
    const fileName = toFileName(className);
    const content = `
# ${fileName}.portulpp (Auto-generated by Aether Core - v2)
# An improved logger with timestamping.
use "native:time"

class ${className} {
    private txt prefix;

    new ${className} txt prefix {
        mov this.prefix prefix;
    }

    public log txt message {
        num timestamp = now;
        put timestamp;
        put " [";
        put this.prefix;
        put "] ";
        put message;
    }
}
`;
    return { content, className };
};


/**
 * Simulates a powerful, local AI model that can synthesize actions from user intent.
 * This is the core of the "offline" command learning feature.
 * @param {string} prompt - The user's command that was not recognized.
 * @param {Language} language - The current UI language for localized responses.
 * @param {'gemini' | 'aether'} aiMode - The AI currently in use.
 * @param {AIPendingAction} [rejectedAction] - The previous action the user rejected, for context.
 * @returns {AIPendingAction} A structured plan for the AI to execute.
 */
export function synthesizeAction(prompt: string, language: Language, aiMode: 'gemini' | 'aether', rejectedAction?: AIPendingAction): AIPendingAction {
    const axiom = getKnowledgeAxiom();
    const t = translations[language];
    const normalizedPrompt = prompt.toLowerCase();

    // --- Synthesis Logic ---

    // Scenario: User wants a logger.
    if (normalizedPrompt.includes('log') || normalizedPrompt.includes('logger') || normalizedPrompt.includes('registro')) {
        // If the user rejected the first logger, offer the advanced one.
        if (rejectedAction && rejectedAction.content.includes("simple utility")) {
             const { content, className } = createAdvancedLoggerCode(axiom);
             const fileName = toFileName(className);
             return {
                originalCommand: prompt,
                actionType: 'CREATE_FILE',
                filePath: `src/utils/${fileName}.portulpp`,
                content: content,
                explanation: `Entendido. El logger simple no fue suficiente.

**Propuesta Alternativa:** He generado un logger más avanzado que incluye un **timestamp** automático en cada mensaje. Usaré el nombre \`${className}\` según mi conocimiento actual.`,
            };
        }

        // Default proposal for a logger.
        const { content, className } = createLoggerCode(axiom);
        const fileName = toFileName(className);
        
        const geminiExplanation = language === 'es' 
? `¡Absolutamente! Puedo construir un componente logger para ti. Aquí está mi proceso de razonamiento:

**1. Análisis de la Petición:**
Solicitas un "logger". Esto se refiere a una utilidad para registrar mensajes, crucial para la depuración.

**2. Estrategia y Diseño:**
*   **Modularidad:** Crearé una clase \`${className}\` en \`Portul++\` para encapsular la lógica.
*   **Ubicación:** Las utilidades van en \`src/utils/\`.
*   **API Simple:** Un constructor para un prefijo y un método \`log\` para los mensajes.
*   **Dependencias del SO:** La función \`put\` se resuelve a través de la Tabla de Importación (IAT) a una llamada del sistema operativo (como \`WriteConsole\`) manejada por el Portul Runtime y \`kernel32.dll\`. No se necesitan DLLs adicionales para esta simple utilidad.

**3. Procedimiento de Implementación:**
*   **Paso 1:** Crear el archivo \`src/utils/${fileName}.portulpp\`.
*   **Paso 2:** Definir la clase \`class ${className}\`.
*   **Paso 3:** Añadir el miembro privado \`private txt prefix\`.
*   **Paso 4:** Implementar el constructor \`new ${className}\`.
*   **Paso 5:** Implementar el método público \`public log\`.

Este enfoque es idiomático en \`Portul++\` y se alinea con los principios de eficiencia.`
: `Absolutely! I can build a logger component for you. Here is my reasoning process:

**1. Request Analysis:**
You're asking for a "logger." This refers to a utility for recording messages, crucial for debugging.

**2. Strategy and Design:**
*   **Modularity:** I will create a \`${className}\` class in \`Portul++\` to encapsulate the logic.
*   **Location:** Utilities belong in \`src/utils/\`.
*   **Simple API:** A constructor for a prefix and a \`log\` method for messages.
*   **OS Dependencies:** The \`put\` function resolves via the Import Address Table (IAT) to an underlying OS call (like \`WriteConsole\`) that is handled by the Portul Runtime and \`kernel32.dll\`. No additional DLLs are needed for this simple utility.

**3. Implementation Procedure:**
*   **Step 1:** Create the file \`src/utils/${fileName}.portulpp\`.
*   **Step 2:** Define the class \`class ${className}\`.
*   **Step 3:** Add the private member \`private txt prefix\`.
*   **Step 4:** Implement the constructor \`new ${className}\`.
*   **Step 5:** Implement the public method \`public log\`.

This approach is idiomatic in \`Portul++\` and aligns with the principles of efficiency.`;

        const aetherExplanation = `He interpretado que necesitas una utilidad para registrar mensajes (un "logger"). Basado en mi conocimiento actual, crearé una clase \`${className}\`.

**Acción Propuesta:** Voy a crear un nuevo archivo en \`src/utils/${fileName}.portulpp\` con una clase \`${className}\` simple que puedes instanciar y usar para imprimir mensajes con un prefijo.`;

        return {
            originalCommand: prompt,
            actionType: 'CREATE_FILE',
            filePath: `src/utils/${fileName}.portulpp`,
            content: content,
            explanation: aiMode === 'gemini' ? geminiExplanation : aetherExplanation,
        };
    }

    // --- Fallback Synthesis ---
    const utilityName = prompt.split(' ').pop() || 'utility';
    const className = toClassName(utilityName, axiom);
    const fileName = toFileName(className);
    
    const geminiExplanation = language === 'es' ? `He analizado tu petición: "${prompt}". Aunque la intención exacta no está pre-programada, puedo deducir que quieres un nuevo componente de utilidad.

**1. Análisis de Intención:**
La petición no coincide con patrones conocidos como "logger", por lo que procederé con una plantilla genérica. El nombre más probable para este componente, basado en tu petición, es \`${utilityName}\`.

**2. Estrategia de Andamiaje (Scaffolding):**
*   Crearé una nueva clase \`${className}\` en un archivo apropiado en \`src/utils/\`.
*   La clase contendrá un constructor básico que imprime un mensaje de confirmación para que sepas que se ha instanciado correctamente.
*   Esto te proporciona una estructura de archivo y clase lista para que puedas añadir tu lógica específica.

**3. Procedimiento de Implementación:**
*   **Paso 1:** Crear el archivo \`src/utils/${fileName}.portulpp\`.
*   **Paso 2:** Definir la clase \`class ${className}\` dentro del archivo.
*   **Paso 3:** Añadir un constructor \`new ${className}\` con una sentencia \`put\` que confirma su creación.`
: `I've analyzed your request: "${prompt}". While the exact intent isn't pre-programmed, I can deduce you want a new utility component.

**1. Intent Analysis:**
The request doesn't match known patterns like "logger," so I will proceed with a generic template. The most likely name for this component, based on your request, is \`${utilityName}\`.

**2. Scaffolding Strategy:**
*   I will create a new class \`${className}\` in an appropriate file under \`src/utils/\`.
*   The class will contain a basic constructor that prints a confirmation message so you know it has been instantiated correctly.
*   This provides you with a file and class structure ready for you to add your specific logic.

**3. Implementation Procedure:**
*   **Step 1:** Create the file \`src/utils/${fileName}.portulpp\`.
*   **Step 2:** Define the class \`class ${className}\` within the file.
*   **Step 3:** Add a constructor \`new ${className}\` with a \`put\` statement confirming its creation.`;

    const aetherExplanation = `No estoy seguro de cómo implementar tu solicitud de "${prompt}", pero puedo crear un archivo base para que empieces. Basado en mi conocimiento actual, lo llamaré \`${className}\`.

**Acción Propuesta:** Voy a crear un nuevo archivo de utilidad en \`src/utils/${fileName}.portulpp\`.`;
    
    return {
        originalCommand: prompt,
        actionType: 'CREATE_FILE',
        filePath: `src/utils/${fileName}.portulpp`,
        content: `# ${fileName}.portulpp (Auto-generated by Aether Core)

class ${className} {
    new ${className} {
        put "Utility for '${prompt}' created.";
    }
}
`,
        explanation: aiMode === 'gemini' ? geminiExplanation : aetherExplanation,
    };
}
